---
- name: nginx systemd
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: nginx restart
  service:
    name=nginx
    state=restarted

- name: php systemd
  systemd:
    name: php8.1-fpm
    enabled: yes
    state: started